In [2]:
# library vs framework
# library: 누군가가 만들어준 클래스 + 함수 -> 직접 구현 안하고 간단하게
# framework: library + 자체 툴 (누군가가 만들어준 틀) -> 그 틀에 맞게 코드를 작성해야 함
# 목표 : BD/AI 관련 라이브러리 사용방법

In [ ]:
# NumPy: 기능 추가된 리스트

# 데이터들 - 일반 리스트
score = [[100, 90, 80], [50,90,30]]
print(score)
print(type(score))
print(score[1])

score[1][0:3] = 0           # error
print(score)

[[100, 90, 80], [50, 90, 30]]
<class 'list'>
[50, 90, 30]


TypeError: can only assign an iterable

In [ ]:
import numpy as np
score2 = np.array([[100, 90, 80], [50,90,30]])
print(score2)
print(type(score2))
print(score2[1])
print(score2[1][2])         # 기존 리스트
print(score2[1, 2])         # NumPy 배열

score2[1, 0:3] = 0          # 가능 -> 한꺼번에 여러 개 수정 가능
print(score2)   

[[100  90  80]
 [ 50  90  30]]
<class 'numpy.ndarray'>
[50 90 30]
30
30
[[100  90  80]
 [  0   0   0]]


In [ ]:
a = [10, 20]
b = [3, 4]
c = a + b                   # 리스트 덧셈 X, 리스트 붙이기
print(c)        

In [ ]:
a2 = np.array([10, 20])
b2 = np.array([3, 4])
c2 = a2 + b2                 # NumPy 배열 덧셈 -> 같은 자리에 있는 것끼리 계산  / 모양 같으면 : 같은 자리에 있는 것끼리 계산
print(c2)   
d2 = a2 * 3                 # Boradcasting: 모양 다르면 : 차원 수 높은 쪽에 맞춰서 계산
print(d2)

[13 24]
[30 60]


In [ ]:
name = np.array(["홍길동", "김철수", "박영희"])
kor = np.array([100, 40, 80])
eng = np.array([90, 50, 70])
math = np.array([80, 30, 60])

total = kor + eng + math
avg = total / 3

print(name)
print(total)
print(avg)

over50 = avg >= 50
print(over50)

result = name[over50]       # masking: True인 index만 출력 -> True인 것의 인덱스에 해당하는 name 출력
print(result)

print(name[kor == 100])
#print(name[(30 < eng) and (eng < 80)])  ->  error: masking에서는 중간에 잘리는 단축 평가 사용 X. 반드시 &, | 사용
print(name[(30 < eng) & (eng < 80)])


['홍길동' '김철수' '박영희']
[270 120 210]
[90. 40. 70.]
[ True False  True]
['홍길동' '박영희']
['홍길동']
['김철수' '박영희']
