In [ ]:
# - 모든 픽셀을 다 숫자로 변환해서 단순 숫자 계산 하는게 맞나?? => 앞에서 한 사진을 픽셀 별로 나눠서 이 칸에는 이거 저 칸에는 저거 틀에 딱 박힌 채로 계산을 하는 것이 맞나 -> 사진의 구도가 조금만 달라져도 다른 결과가 나오게 됨
# - 위치별 패텬 파악하는게 맞지 않을까? -> 머리 밑에 목, 목 믿에 몸통... => 모든 픽셀을 다 볼 필요가 없어짐

# CNN(Convolutional NN): 합성곱 신경망
#   kernel/filter로 긁어가면서
#       주변만 연결하여 결과 내서 -> 위치정보에 대한 결과
#       다양한 특성을 가진 kernel로 긁어서 channel 축으로 쌓아서 -> 이미지의 특성 
#   - padding: 데이터 바깥쪽에 추가해서 kernel로 긁어도 데이터의 사이즈가 줄지 않게 해주는 것
#   - stride: kernel이 얼마씩 움직일지
#   - (max/avg) pooling: 대푯값 뽑기 (kernel 범위 내에서 최대/평균)
# => 여러 층의 CNN을 통과하고 (위치별 특성 추출), 마지막에 FC(Fully Connected) Layer(위치별 특성 추출해놓은 것 전체)를 통과
# => 어떤 이미지가 있을 때 kernelSize? padding? strid? pooling? 각 값들을 얼마 줘야 이미지 인식을 잘 할까? : 노가다 -> 계속 바꿔가면서 적절한 값을 찾아내야함
# -> AI 연구하는 사람들이 노가다를 해서 최적의 모델들을 만들어놨음(Resnet, ...)

In [1]:
import torch
from torch import nn, optim
from torch.utils.data import Dataset,DataLoader # PyTorch에서 제공하는 데이터 관련 라이브러리

# 이미지 파일 불러오기
import cv2
import numpy as np
import os

# 데이터를 훈련/검증용으로 나누기 위해
from random import random

In [2]:
device = "cpu"

In [7]:
def getImg(folder, w, h):  
    trainData, trainLabel, testData, testLabel = [], [], [],[]                    
    for f in os.listdir(folder):                # 사진 가로, 세로 = 행열
        data = cv2.imread(folder + "/" + f, cv2.IMREAD_GRAYSCALE)
        data = cv2.resize(data, (w, h))
        print(data)
    return trainData, trainLabel, testData, testLabel

In [9]:
label = ["떡볶이", "오뎅", "김밥", "튀김", "순대"]
yData = [0,0,0,0,0, 1,1,1,1,1, 2,2,2,2,2, 3,3,3,3,3, 4,4,4,4,4]         


trainData, trainLabel, testData, testLabel = getImg("./Users/stu_ict01_01/Jun04_1_DeepLearning/bunsikMenu", 100, 50)

[[221 221 220 ... 219 219 219]
 [220 221 219 ... 218 219 218]
 [220 221 219 ... 218 219 218]
 ...
 [218 218 218 ... 219 221 221]
 [218 220 220 ... 220 220 223]
 [220 219 219 ... 220 221 223]]
[[218 218 218 ... 217 218 218]
 [218 218 218 ... 218 218 218]
 [218 218 218 ... 218 218 218]
 ...
 [219 219 219 ... 216 216 216]
 [219 219 219 ... 216 216 216]
 [219 219 219 ... 217 216 216]]
[[216 215 216 ... 217 215 215]
 [216 216 215 ... 218 217 217]
 [216 216 215 ... 218 217 217]
 ...
 [216 216 218 ... 215 213 213]
 [215 217 217 ... 215 214 214]
 [216 217 216 ... 215 213 213]]
[[214 215 215 ... 213 213 213]
 [214 214 214 ... 213 213 213]
 [214 214 214 ... 213 213 213]
 ...
 [215 217 217 ... 213 213 213]
 [215 215 215 ... 213 213 213]
 [214 215 215 ... 213 213 213]]
[[212 212 212 ... 209 209 209]
 [212 213 213 ... 209 209 209]
 [212 213 213 ... 209 209 209]
 ...
 [209 209 209 ... 207 206 207]
 [209 209 209 ... 207 206 207]
 [209 209 209 ... 207 207 209]]
[[216 216 215 ... 220 220 220]
 [217 217